# https://docs.travis-ci.com/user/languages/python/
language: python
python:
#  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
#  - "3.9-dev"  # 3.9 development branch
#  - "nightly"  # nightly build

# command to install dependencies
install:
  - |
    sudo apt-get -y install wget tar
    rm -rf linux_amd64.tar.gz weed
    wget --quiet https://github.com/chrislusf/seaweedfs/releases/download/2.21/linux_amd64.tar.gz
    tar xf linux_amd64.tar.gz
    chmod +x weed
    mkdir -p data/volume1 data/volume2
    ./weed master > weed_master.log 2>&1 &
    ./weed volume -dir="./data/volume1" -max=5  -mserver="localhost:9333" -port=27000 > weed_volume_1.log 2>&1 &
    ./weed volume -dir="./data/volume2" -max=5  -mserver="localhost:9333" -port=27001 > weed_volume_2.log 2>&1 &
    ./weed filer -port=27100 -master="localhost:9333" > weed_filer.log 2>&1 &
    echo "started all weed services"
#    pip install --upgrade pip
#    pip install pytest
#    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #        pip install -e . > /dev/null 2>&1 &
    echo "pwd is $(pwd)"
    ls -alh
  - pip install -r requirements.txt
#  - pip install -e . > /dev/null 2>&1 &

# command to run tests
script:
  - pytest .